### GET request to example server
GET http://localhost:8080/calculate?eq=(7-3)*2
###

### GET request to example server
GET http://localhost:8080/calculate?eq=90/9*8
###

### GET request to example server
GET http://localhost:8080/calculate?eq=((7%2B3)%2B5%2B9*(100/5))/(10/2)
###

### GET request to example server
GET http://localhost:8080/calculate?eq=5 * 3 %2B 100 - (15 - 3 / 15) %2B (1.5 * 7.254 * 15)
###